//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westwind.RazorHosting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Westwind.RazorHosting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t activate type instance: .
        /// </summary>
        internal static string CouldnTActivateTypeInstance {
            get {
                return ResourceManager.GetString("CouldnTActivateTypeInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading template file: .
        /// </summary>
        internal static string ErrorReadingTemplateFile {
            get {
                return ResourceManager.GetString("ErrorReadingTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0}\t Col: {1}\t Error: {2}
        ///.
        /// </summary>
        internal static string LineX0TColX1TErrorX2RN {
            get {
                return ResourceManager.GetString("LineX0TColX1TErrorX2RN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Rendering failed for {0}: {1}.
        /// </summary>
        internal static string PartialRenderingFailed {
            get {
                return ResourceManager.GetString("PartialRenderingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously compiled assembly not found..
        /// </summary>
        internal static string PreviouslyCompiledAssemblyNotFound {
            get {
                return ResourceManager.GetString("PreviouslyCompiledAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Execution Error: .
        /// </summary>
        internal static string TemplateExecutionError {
            get {
                return ResourceManager.GetString("TemplateExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template File doesn&apos;t exist: .
        /// </summary>
        internal static string TemplateFileDoesnTExist {
            get {
                return ResourceManager.GetString("TemplateFileDoesnTExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create type  .
        /// </summary>
        internal static string UnableToCreateType {
            get {
                return ResourceManager.GetString("UnableToCreateType", resourceCulture);
            }
        }
    }
}
